Добавлен класс УправлениеАС
vanessa-opensource/ibcmdrunner pull request #3
Opened 2024-07-03 21:36 UTC by yukon39

Добавлен класс управления запуском автономного сервера.

Closes [#9](https://github.com/alex-bob-lip/ibcmdrunner/issues/9)

2024-11-14 17:17 UTC, artbear commented on src/Классы/ibsrvrunner.os
> +	Ожидаем.Что(НомерВерсии).ИмеетТип("Строка");
не подключено #Использовать asserts, но используется Ожидаем !

2024-11-14 17:54 UTC, artbear requested changes
есть замечания.

2024-11-14 17:54 UTC, artbear commented on src/Классы/configfile_as.os
> +//   ТипОтладки - Строка - Режим работы отладчика. (tcp|http)
в описании стоит указать, что возможно ТипОтладки = "none" или явно использовать пустое значение по умолчанию, что проще всего

2024-11-14 18:29 UTC, yukon39 commented on src/Классы/ibsrvrunner.os
> +Процедура УстановитьПараметрыФайловойИБ(Знач КаталогИБ) Экспорт
Разумно. Вообще на примере конфигурационного файла АС я бы поменьше использовал методы для групповой установки параметров.

2024-11-14 18:34 UTC, yukon39 commented on src/Классы/ibsrvrunner.os
> +Процедура УстановитьПараметрыФайловойИБ(Знач КаталогИБ) Экспорт
Неа, такой же метод есть в ibcmdrunner. Лучше оставить единообразно.

2024-11-14 18:42 UTC, yukon39 commented on src/Классы/configfile_as.os
> +Процедура ПараметрыФайловойБД(ПутьКФайлуИБ) Экспорт
Точно. Логин и пароль к ИБ указываются уже клиентской частью 1С при подключении.

2024-11-14 19:01 UTC, yukon39 commented on src/Классы/ibsrvrunner.os
> +	Ожидаем.Что(НомерВерсии).ИмеетТип("Строка");
исправлено

2024-11-14 19:01 UTC, yukon39 commented on src/Классы/ibsrvrunner.os
> +	Ожидаем.Что(Разрядность).ИмеетТип("Строка");
исправлено

2024-11-14 19:02 UTC, yukon39 commented on src/Классы/ibsrvrunner.os
> +Процедура ibsrv_Версия(НомерВерсии, Разрядность)
исправлено

2024-11-14 19:02 UTC, yukon39 commented on src/Классы/ibsrvrunner.os
> +	Ожидаем.Что(НомерПорта).Меньше(65535); // BSLLS:MagicNumber-off
исправлено

2024-11-14 19:02 UTC, yukon39 commented on src/Классы/ibsrvrunner.os
> +	Ожидаем.Что(НомерПорта).Меньше(65535); // BSLLS:MagicNumber-off
исправлено

2024-11-14 19:02 UTC, yukon39 commented on src/Классы/configfile_as.os
> +Процедура ПараметрыСервера(Порт = 8314,
исправлено

2024-11-14 19:03 UTC, yukon39 commented on src/Классы/configfile_as.os
> +//   ТипОтладки - Строка - Режим работы отладчика. (tcp|http)
исправлено

2024-11-14 19:14 UTC, yukon39 commented on src/Классы/ibsrvrunner.os
> +		ИначеЕсли ТипЗнч(КлючИЗначение.Значение) = Тип("Число") Тогда
Перебдел :) Лучше оставить числа в Параметрах, а уже обертку делать единообразно для всех чисел.

2024-11-14 19:18 UTC, yukon39 commented on src/Классы/ibsrvrunner.os
> +Функция ЗапуститьПроцессIbsrv(Знач ПараметрыКоманды)
Нет тут он специально меняется так, чтобы сформировать командную строку. С внешней стороны это изменение не должно быть доступно.

2024-11-15 18:22 UTC, artbear commented on src/Классы/ibsrvrunner.os
> +		Если КлючИЗначение.Значение = Неопределено Тогда // это параметр-флаг
пока даже этих параметров нет, давай 
- этот код сдвинем в конец вычисления, после проверки прочих условий
- вдруг случайно в значения попадут Неопределено для других типов данных, тогда вся обработка пойдет неверно

2024-11-16 09:55 UTC, merged