https://github.com/vanessa-opensource/ibcmdrunner/issues/6
vanessa-opensource/ibcmdrunner pull request #8
Opened 2024-12-14 19:10 UTC by yuriybylinkin

2024-12-22 11:40 UTC, artbear requested changes

2024-12-22 11:40 UTC, artbear commented on src/Классы/ibcmdrunner.os
> +            Если ОписаниеРасширения.Получить(ИмяСвойства) = Неопределено Тогда
этот код будет пропускать свойства, не указанные в НовыйОписаниеРасширения.

т.е. можем пропустить свойства, которые будут добавлены в будущих версиях ibsrv

2024-12-22 15:47 UTC, yuriybylinkin commented on src/Классы/ibcmdrunner.os
> +            Если ОписаниеРасширения.Получить(ИмяСвойства) = Неопределено Тогда
Согласен, исправил.
Плюс добавил преобразование no и yes в булево

2024-12-23 06:29 UTC, artbear approved these changes

2024-12-23 06:29 UTC, merged